name: Frontend Lint

on:
  push:
    branches:
      - main # 或你希望触发的分支
      - develop
  pull_request:
    branches:
      - main # PR 时也可以触发

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint # 这里的 lint 命令根据你的 package.json 配置
